#!/usr/bin/env bash
# ralph.sh — the Ralph Wiggum loop wrapper
# Generated by cortex-x /ralph-loop skill from templates/ralph.template.sh
# Usecase: {{USECASE}}
# Generated at: {{TIMESTAMP}}
# Branch: {{BRANCH}}
# Baseline commit: {{BASELINE_SHA}}
#
# Recovery: git reset --hard {{BASELINE_SHA}}
# Killswitch: touch ~/.cortex/STEWARD_HALT  (next iteration exits cleanly)
# Monitor: tail -f cortex/ralph/{{USECASE_SLUG}}/journal.jsonl

# Note: we DON'T use `set -e` here — the loop is built around tolerating
# non-zero exits from individual iterations + arithmetic that returns 0
# from $((...)) (which counts as exit 1 under set -e and would silently
# kill the loop on iter 1). We catch failures explicitly per command.
set -uo pipefail

# === Configurable caps (operator can override via env before invocation) ===
MAX_ITERATIONS="${MAX_ITERATIONS:-50}"
MAX_HOURS="${MAX_HOURS:-8}"
MAX_COST_USD="${MAX_COST_USD:-20}"
MAX_TOKENS_PER_HOUR="${MAX_TOKENS_PER_HOUR:-200000}"
MODEL="${RALPH_MODEL:-claude-sonnet-4-6}"
MODE="${RALPH_MODE:-builder-only}"  # planner-only | builder-only | planner-then-builder | single-pass

# === Paths ===
RALPH_DIR="$(cd "$(dirname "$0")" && pwd)"
PROMPT_FILE="$RALPH_DIR/PROMPT.md"
FIX_PLAN="$RALPH_DIR/fix_plan.md"
JOURNAL="$RALPH_DIR/journal.jsonl"
STATUS_LINK="$RALPH_DIR/STATUS"
COST_FILE="$RALPH_DIR/COST"
REPORT="$RALPH_DIR/REPORT.md"
HALT_FILE="$HOME/.cortex/STEWARD_HALT"

# === Pre-flight ===
if [ ! -f "$PROMPT_FILE" ]; then
  echo "ERROR: $PROMPT_FILE missing — run /ralph-loop to scaffold." >&2
  exit 2
fi
if [ ! -f "$FIX_PLAN" ]; then
  echo "ERROR: $FIX_PLAN missing — run /ralph-loop to scaffold." >&2
  exit 2
fi
if ! command -v claude >/dev/null 2>&1; then
  echo "ERROR: claude CLI not found in PATH." >&2
  exit 2
fi

# Refuse if fix_plan has zero unchecked items at start — that's "never
# populated", not "completed" (would otherwise emit a misleading success
# REPORT.md on iter 0).
if ! grep -q '^- \[ \]' "$FIX_PLAN"; then
  echo "ERROR: $FIX_PLAN has zero unchecked '- [ ]' items. Add items before running." >&2
  exit 2
fi

# Refuse if git tree dirty — Ralph commits per iteration, must start clean.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  echo "ERROR: git tree dirty. Commit or stash before running." >&2
  exit 2
fi

# Refuse if branch is main — Ralph commits autonomously, never on main.
CUR_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [ "$CUR_BRANCH" = "main" ] || [ "$CUR_BRANCH" = "master" ]; then
  echo "ERROR: refuse to run on '$CUR_BRANCH'. Create a ralph/<usecase> branch." >&2
  exit 2
fi

# Refuse if STEWARD_HALT killswitch is set (Ralph respects the same halt).
if [ -f "$HALT_FILE" ]; then
  echo "ERROR: $HALT_FILE exists — operator halted all cortex agents. Remove to resume." >&2
  exit 2
fi

# Process lock — refuse if another ralph.sh is running for the same usecase.
LOCK_FILE="$RALPH_DIR/ralph.pid"
if [ -f "$LOCK_FILE" ]; then
  EXISTING_PID=$(cat "$LOCK_FILE" 2>/dev/null || echo "")
  if [ -n "$EXISTING_PID" ] && kill -0 "$EXISTING_PID" 2>/dev/null; then
    echo "ERROR: ralph.sh already running (PID $EXISTING_PID). Stop it or rm $LOCK_FILE if stale." >&2
    exit 2
  fi
  rm -f "$LOCK_FILE"
fi
echo "$$" > "$LOCK_FILE"

# Refuse if jq missing — without it cost cap silently fails open ($0 forever).
if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq not in PATH. Cost cap depends on it. Install jq (apt/brew/choco) and retry." >&2
  rm -f "$LOCK_FILE"
  exit 2
fi

# SIGINT/SIGTERM trap: write final journal line + clean lock.
cleanup() {
  local sig="${1:-EXIT}"
  if [ "$sig" != "EXIT" ]; then
    printf '{"iteration":%d,"epoch":%d,"exit_reason":"SIGNAL_%s"}\n' \
      "${iter:-0}" "$(date +%s)" "$sig" >> "$JOURNAL" 2>/dev/null || true
  fi
  rm -f "$LOCK_FILE"
}
trap 'cleanup INT;  exit 130' INT
trap 'cleanup TERM; exit 143' TERM
trap 'cleanup EXIT'           EXIT

# === Circuit-breaker counters (in-memory; reset on script restart) ===
no_progress_count=0
consecutive_error_signature=""
consecutive_error_count=0
consecutive_reset_count=0
total_cost_usd=0
iter=0
start_epoch=$(date +%s)

echo "0" > "$COST_FILE"
echo "ralph: starting loop. usecase={{USECASE}}, mode=$MODE, max_iter=$MAX_ITERATIONS, max_hours=$MAX_HOURS, max_cost_usd=$MAX_COST_USD" \
  | tee -a "$JOURNAL"

journal_line() {
  # $1 = JSON-fragment (no leading/trailing braces)
  local epoch
  epoch=$(date +%s)
  printf '{"iteration":%d,"epoch":%d,%s}\n' "$iter" "$epoch" "$1" >> "$JOURNAL"
}

check_termination() {
  # Returns: 0 = continue, 1 = stop. Prints reason to stderr on stop.

  if [ -f "$HALT_FILE" ]; then
    echo "STEWARD_HALT" >&2
    journal_line '"exit_reason":"STEWARD_HALT"'
    return 1
  fi

  if [ "$iter" -ge "$MAX_ITERATIONS" ]; then
    echo "MAX_ITERATIONS_REACHED ($MAX_ITERATIONS)" >&2
    journal_line "\"exit_reason\":\"MAX_ITERATIONS_REACHED\",\"iterations\":$iter"
    return 1
  fi

  local elapsed_hours=0
  # $((...)) returning 0 sets exit code 1 — capture explicitly so set -e
  # (if re-enabled by an operator) doesn't kill the loop in hour zero.
  : $(( elapsed_hours = ( $(date +%s) - start_epoch ) / 3600 ))
  if [ "$elapsed_hours" -ge "$MAX_HOURS" ]; then
    echo "MAX_HOURS_REACHED ($MAX_HOURS)" >&2
    journal_line "\"exit_reason\":\"MAX_HOURS_REACHED\",\"elapsed_hours\":$elapsed_hours"
    return 1
  fi

  # awk dollar compare (bash can't do float; awk returns 1 if cost >= cap)
  if awk -v c="$total_cost_usd" -v m="$MAX_COST_USD" 'BEGIN{exit !(c>=m)}'; then
    echo "MAX_COST_USD_REACHED ($total_cost_usd >= $MAX_COST_USD)" >&2
    journal_line "\"exit_reason\":\"MAX_COST_USD_REACHED\",\"total_cost_usd\":$total_cost_usd"
    return 1
  fi

  # Primary success exit: fix_plan has zero unchecked items
  if ! grep -q '^- \[ \]' "$FIX_PLAN"; then
    echo "FIX_PLAN_EMPTY (primary success)" >&2
    journal_line '"exit_reason":"FIX_PLAN_EMPTY"'
    return 1
  fi

  if [ "$no_progress_count" -ge 3 ]; then
    echo "NO_PROGRESS (3+ iterations without items closed)" >&2
    journal_line "\"exit_reason\":\"NO_PROGRESS\",\"streak\":$no_progress_count"
    return 1
  fi

  if [ "$consecutive_error_count" -ge 5 ]; then
    echo "STUCK_ERROR (5+ identical errors)" >&2
    journal_line "\"exit_reason\":\"STUCK_ERROR\",\"streak\":$consecutive_error_count,\"signature\":\"$consecutive_error_signature\""
    return 1
  fi

  if [ "$consecutive_reset_count" -ge 2 ]; then
    echo "CORRUPTION (2+ consecutive git reset --hard events)" >&2
    journal_line "\"exit_reason\":\"CORRUPTION\",\"streak\":$consecutive_reset_count"
    return 1
  fi

  return 0
}

# === Main loop ===
while check_termination; do
  iter=$((iter + 1))
  iter_start=$(date +%s)
  echo "ralph: iteration $iter starting at $(date -Is)" | tee -a "$JOURNAL"

  # Count items before
  open_before=$(grep -c '^- \[ \]' "$FIX_PLAN" 2>/dev/null || echo 0)
  closed_before=$(grep -c '^- \[x\]' "$FIX_PLAN" 2>/dev/null || echo 0)

  # Iteration log lives in $RALPH_DIR/iter-$iter.log; STATUS points at it.
  # Use `ln -sfn` for atomic replace (avoids TOCTOU between rm and ln).
  # Falls back to a plain text file if symlinks aren't supported (Win Git Bash
  # without Developer Mode).
  iter_log="$RALPH_DIR/iter-$iter.log"
  if ! ln -sfn "$(basename "$iter_log")" "$STATUS_LINK" 2>/dev/null; then
    echo "$iter_log" > "$STATUS_LINK"
  fi

  # Invoke claude headless. --dangerously-skip-permissions is a CONVENIENCE
  # flag for unattended runs; it disables Claude Code's permission-prompt
  # defense (including the block-destructive hook). We rely instead on:
  #   - pre-flight gates above (clean tree, non-main branch, no STEWARD_HALT,
  #     ≥1 fix_plan item, jq present)
  #   - circuit breakers (no-progress, stuck-error, corruption)
  #   - operator review of fix_plan.md (untrusted content delimiters)
  #   - the operator running this on a ralph/<usecase> branch they control
  # For higher-stakes runs, set RALPH_REQUIRE_HOOKS=1 and run without the flag
  # — slower (prompts on each tool call) but defense-in-depth intact.
  # Per-iteration wall-clock cap (default: cap_hours/iterations × 2)
  PER_ITER_TIMEOUT="${PER_ITER_TIMEOUT:-$(( MAX_HOURS * 3600 * 2 / MAX_ITERATIONS ))}"
  CLAUDE_PERMS_FLAG="--dangerously-skip-permissions"
  if [ "${RALPH_REQUIRE_HOOKS:-0}" = "1" ]; then
    CLAUDE_PERMS_FLAG="--permission-mode=acceptEdits"
  fi
  if command -v timeout >/dev/null 2>&1; then
    timeout "$PER_ITER_TIMEOUT" bash -c "cat \"$PROMPT_FILE\" | claude -p $CLAUDE_PERMS_FLAG --model \"$MODEL\" --output-format stream-json --verbose" \
      > "$iter_log" 2>&1
    iter_exit=$?
  else
    cat "$PROMPT_FILE" | claude -p $CLAUDE_PERMS_FLAG --model "$MODEL" --output-format stream-json --verbose \
      > "$iter_log" 2>&1
    iter_exit=$?
  fi

  iter_end=$(date +%s)
  iter_seconds=$((iter_end - iter_start))

  # Extract cost from the stream-json. Output is NDJSON (one JSON per line),
  # so jq runs per-line (default mode). Take the last `result` event because
  # subagent fanout emits intermediate result events; only the top-level run's
  # final event carries the rolled-up total_cost_usd.
  iter_cost=0
  if command -v jq >/dev/null 2>&1; then
    iter_cost=$(jq -r 'select(.type == "result") | .total_cost_usd // 0' "$iter_log" 2>/dev/null | tail -1)
    [ -z "$iter_cost" ] && iter_cost=0
  fi
  total_cost_usd=$(awk -v a="$total_cost_usd" -v b="$iter_cost" 'BEGIN{printf "%.4f", a+b}')
  echo "$total_cost_usd" > "$COST_FILE"

  # Count items after
  open_after=$(grep -c '^- \[ \]' "$FIX_PLAN" 2>/dev/null || echo 0)
  closed_after=$(grep -c '^- \[x\]' "$FIX_PLAN" 2>/dev/null || echo 0)
  items_closed=$((closed_after - closed_before))
  items_added=$((open_after - open_before + items_closed))

  # Circuit-breaker updates
  if [ "$items_closed" -eq 0 ]; then
    no_progress_count=$((no_progress_count + 1))
  else
    no_progress_count=0
  fi

  # Error signature = last non-empty stderr-ish line in the iter log
  iter_error_sig=$(tail -200 "$iter_log" | grep -i 'error\|failed\|exception' | tail -1 | head -c 200)
  if [ -n "$iter_error_sig" ] && [ "$iter_error_sig" = "$consecutive_error_signature" ]; then
    consecutive_error_count=$((consecutive_error_count + 1))
  else
    consecutive_error_signature="$iter_error_sig"
    consecutive_error_count=1
  fi

  # Corruption detection — model destructively rewound the tree. Snapshot
  # rev-parse before/after each iteration: HEAD moving backwards in history
  # OR commit-count dropping = a `git reset --hard` / `git checkout -f` /
  # `git clean -fdx` happened.
  cur_head=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
  cur_commit_count=$(git rev-list --count HEAD 2>/dev/null || echo 0)
  if [ "${prev_commit_count:-}" != "" ] && [ "$cur_commit_count" -lt "${prev_commit_count}" ]; then
    consecutive_reset_count=$((consecutive_reset_count + 1))
  else
    consecutive_reset_count=0
  fi
  prev_commit_count="$cur_commit_count"
  prev_head="$cur_head"

  journal_line "\"items_closed\":$items_closed,\"items_added\":$items_added,\"iter_seconds\":$iter_seconds,\"iter_cost_usd\":$iter_cost,\"total_cost_usd\":$total_cost_usd,\"iter_exit\":$iter_exit"

  echo "ralph: iter $iter done. closed=$items_closed added=$items_added seconds=$iter_seconds cost=$iter_cost total=$total_cost_usd" \
    | tee -a "$JOURNAL"

  # single-pass mode = run one iteration and stop
  if [ "$MODE" = "single-pass" ]; then
    echo "SINGLE_PASS_DONE" >&2
    journal_line '"exit_reason":"SINGLE_PASS_DONE"'
    break
  fi
done

# === Post-loop summary ===
final_open=$(grep -c '^- \[ \]' "$FIX_PLAN" 2>/dev/null || echo 0)
final_closed=$(grep -c '^- \[x\]' "$FIX_PLAN" 2>/dev/null || echo 0)
final_elapsed=$(( $(date +%s) - start_epoch ))

cat > "$REPORT" <<REPORT_EOF
# Ralph run report — {{USECASE}}

- **Iterations**: $iter (cap $MAX_ITERATIONS)
- **Elapsed**: $((final_elapsed / 60)) min (cap $((MAX_HOURS * 60)) min)
- **Cost**: \$$total_cost_usd (cap \$$MAX_COST_USD)
- **Items closed**: $final_closed
- **Items still open**: $final_open
- **Branch**: {{BRANCH}}
- **Baseline**: {{BASELINE_SHA}}

## Next actions
1. Read \`fix_plan.md\` — any \`> blocker:\` or \`> human-needed:\` notes need operator review
2. Run \`npm test\` (or equivalent) to confirm full suite is green
3. Spawn R2 review pipeline against the full diff: \`git diff {{BASELINE_SHA}}..HEAD\`
4. If clean, open PR. If not, either run another \`./ralph.sh\` after editing fix_plan, or \`git reset --hard {{BASELINE_SHA}}\` to abandon.

## Journal
\`cat journal.jsonl\` for per-iteration detail.
REPORT_EOF

echo "ralph: loop exited. report=$REPORT" | tee -a "$JOURNAL"
