# ralph.ps1 — the Ralph Wiggum loop wrapper (PowerShell variant)
# Generated by cortex-x /ralph-loop skill from templates/ralph.template.ps1
# Usecase: {{USECASE}}
# Generated at: {{TIMESTAMP}}
# Branch: {{BRANCH}}
# Baseline commit: {{BASELINE_SHA}}
#
# Recovery:  git reset --hard {{BASELINE_SHA}}
# Killswitch: New-Item -ItemType File -Force "$env:USERPROFILE\.cortex\STEWARD_HALT"
# Monitor:   Get-Content -Wait cortex/ralph/{{USECASE_SLUG}}/journal.jsonl

$ErrorActionPreference = 'Stop'

# === Configurable caps (operator can override via env before invocation) ===
$MaxIterations    = [int]($env:MAX_ITERATIONS    | Where-Object { $_ }) ; if (-not $MaxIterations)    { $MaxIterations    = 50 }
$MaxHours         = [int]($env:MAX_HOURS         | Where-Object { $_ }) ; if (-not $MaxHours)         { $MaxHours         = 8 }
$MaxCostUsd       = [double]($env:MAX_COST_USD   | Where-Object { $_ }) ; if (-not $MaxCostUsd)       { $MaxCostUsd       = 20 }
$MaxTokensPerHour = [int]($env:MAX_TOKENS_PER_HOUR | Where-Object { $_ }) ; if (-not $MaxTokensPerHour) { $MaxTokensPerHour = 200000 }
$Model            = if ($env:RALPH_MODEL) { $env:RALPH_MODEL } else { 'claude-sonnet-4-6' }
$Mode             = if ($env:RALPH_MODE)  { $env:RALPH_MODE  } else { 'builder-only' }

# === Paths ===
$RalphDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$PromptFile = Join-Path $RalphDir 'PROMPT.md'
$FixPlan    = Join-Path $RalphDir 'fix_plan.md'
$Journal    = Join-Path $RalphDir 'journal.jsonl'
$StatusLink = Join-Path $RalphDir 'STATUS'
$CostFile   = Join-Path $RalphDir 'COST'
$Report     = Join-Path $RalphDir 'REPORT.md'
$HaltFile   = Join-Path $env:USERPROFILE '.cortex/STEWARD_HALT'

# === Pre-flight ===
if (-not (Test-Path $PromptFile)) {
    Write-Error "PROMPT.md missing — run /ralph-loop to scaffold."
    exit 2
}
if (-not (Test-Path $FixPlan)) {
    Write-Error "fix_plan.md missing — run /ralph-loop to scaffold."
    exit 2
}
if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Write-Error "claude CLI not found in PATH."
    exit 2
}

# === Circuit-breaker counters ===
$noProgressCount        = 0
$consecutiveErrorSig    = ''
$consecutiveErrorCount  = 0
$consecutiveResetCount  = 0
$totalCostUsd           = 0.0
$iter                   = 0
$startEpoch             = [int][DateTimeOffset]::Now.ToUnixTimeSeconds()

'0' | Out-File -Encoding ascii $CostFile
"ralph: starting loop. usecase={{USECASE}}, mode=$Mode, max_iter=$MaxIterations, max_hours=$MaxHours, max_cost_usd=$MaxCostUsd" `
    | Tee-Object -FilePath $Journal -Append

function Add-JournalLine([string]$Fragment) {
    $epoch = [int][DateTimeOffset]::Now.ToUnixTimeSeconds()
    "{`"iteration`":$iter,`"epoch`":$epoch,$Fragment}" | Out-File -Encoding ascii -Append $Journal
}

function Test-Termination {
    if (Test-Path $HaltFile) {
        Write-Host 'STEWARD_HALT' -ForegroundColor Yellow
        Add-JournalLine '"exit_reason":"STEWARD_HALT"'
        return $true
    }
    if ($iter -ge $MaxIterations) {
        Write-Host "MAX_ITERATIONS_REACHED ($MaxIterations)" -ForegroundColor Yellow
        Add-JournalLine "`"exit_reason`":`"MAX_ITERATIONS_REACHED`",`"iterations`":$iter"
        return $true
    }
    $elapsedHours = [int](([int][DateTimeOffset]::Now.ToUnixTimeSeconds() - $startEpoch) / 3600)
    if ($elapsedHours -ge $MaxHours) {
        Write-Host "MAX_HOURS_REACHED ($MaxHours)" -ForegroundColor Yellow
        Add-JournalLine "`"exit_reason`":`"MAX_HOURS_REACHED`",`"elapsed_hours`":$elapsedHours"
        return $true
    }
    if ($totalCostUsd -ge $MaxCostUsd) {
        Write-Host "MAX_COST_USD_REACHED ($totalCostUsd >= $MaxCostUsd)" -ForegroundColor Yellow
        Add-JournalLine "`"exit_reason`":`"MAX_COST_USD_REACHED`",`"total_cost_usd`":$totalCostUsd"
        return $true
    }
    if (-not (Select-String -Path $FixPlan -Pattern '^- \[ \]' -Quiet -SimpleMatch:$false)) {
        Write-Host 'FIX_PLAN_EMPTY (primary success)' -ForegroundColor Green
        Add-JournalLine '"exit_reason":"FIX_PLAN_EMPTY"'
        return $true
    }
    if ($noProgressCount -ge 3) {
        Write-Host "NO_PROGRESS ($noProgressCount iterations without items closed)" -ForegroundColor Yellow
        Add-JournalLine "`"exit_reason`":`"NO_PROGRESS`",`"streak`":$noProgressCount"
        return $true
    }
    if ($consecutiveErrorCount -ge 5) {
        Write-Host "STUCK_ERROR ($consecutiveErrorCount identical errors)" -ForegroundColor Yellow
        Add-JournalLine "`"exit_reason`":`"STUCK_ERROR`",`"streak`":$consecutiveErrorCount"
        return $true
    }
    if ($consecutiveResetCount -ge 2) {
        Write-Host 'CORRUPTION (2+ consecutive git reset --hard events)' -ForegroundColor Red
        Add-JournalLine "`"exit_reason`":`"CORRUPTION`",`"streak`":$consecutiveResetCount"
        return $true
    }
    return $false
}

# === Main loop ===
while (-not (Test-Termination)) {
    $iter += 1
    $iterStart = [int][DateTimeOffset]::Now.ToUnixTimeSeconds()
    "ralph: iteration $iter starting at $(Get-Date -Format o)" | Tee-Object -FilePath $Journal -Append

    $openBefore   = @(Select-String -Path $FixPlan -Pattern '^- \[ \]').Count
    $closedBefore = @(Select-String -Path $FixPlan -Pattern '^- \[x\]').Count

    $iterLog = Join-Path $RalphDir "iter-$iter.log"
    if (Test-Path $StatusLink) { Remove-Item $StatusLink -Force }
    # PowerShell symbolic links require admin on most setups — fall back to plain copy of path into STATUS
    "$iterLog" | Out-File -Encoding ascii $StatusLink

    # Invoke claude headless (see ralph.template.sh for the discussion of
    # why --dangerously-skip-permissions is required here, and what gates
    # the loop on before allowing it).
    # -Raw avoids the PS object pipeline re-stringifying with CRLF+BOM, which
    # the model otherwise sees as a corrupted prompt. RALPH_REQUIRE_HOOKS=1
    # swaps --dangerously-skip-permissions for the safer acceptEdits mode.
    $permsFlag = if ($env:RALPH_REQUIRE_HOOKS -eq '1') { '--permission-mode=acceptEdits' } else { '--dangerously-skip-permissions' }
    $promptText = Get-Content -Raw $PromptFile
    try {
        $promptText | claude -p $permsFlag --model $Model --output-format stream-json --verbose *> $iterLog
        $iterExit = $LASTEXITCODE
    } catch {
        $iterExit = -1
    }

    $iterEnd = [int][DateTimeOffset]::Now.ToUnixTimeSeconds()
    $iterSeconds = $iterEnd - $iterStart

    $iterCost = 0.0
    if (Get-Command jq -ErrorAction SilentlyContinue) {
        try {
            $iterCost = [double]((jq -r '. | select(.type == "result") | .total_cost_usd // 0' $iterLog 2>$null) -split "`n" | Where-Object { $_ } | Select-Object -Last 1)
        } catch { $iterCost = 0.0 }
    }
    $totalCostUsd = [math]::Round($totalCostUsd + $iterCost, 4)
    $totalCostUsd | Out-File -Encoding ascii $CostFile

    $openAfter   = @(Select-String -Path $FixPlan -Pattern '^- \[ \]').Count
    $closedAfter = @(Select-String -Path $FixPlan -Pattern '^- \[x\]').Count
    $itemsClosed = $closedAfter - $closedBefore
    $itemsAdded  = $openAfter - $openBefore + $itemsClosed

    if ($itemsClosed -eq 0) { $noProgressCount += 1 } else { $noProgressCount = 0 }

    $errorMatch = Get-Content $iterLog -Tail 200 -ErrorAction SilentlyContinue | Select-String -Pattern '^(Error|FAIL|FATAL)|"type":\s*"error"' | Select-Object -Last 1
    $iterErrorSig = if ($null -ne $errorMatch) { $errorMatch.ToString() } else { '' }
    if ($iterErrorSig -and $iterErrorSig -eq $consecutiveErrorSig) {
        $consecutiveErrorCount += 1
    } else {
        $consecutiveErrorSig = $iterErrorSig
        $consecutiveErrorCount = if ($iterErrorSig) { 1 } else { 0 }
    }

    # Corruption detection — snapshot HEAD + commit count, compare to previous.
    # Catches `git reset --hard`, `git checkout -f`, `git clean -fdx`, etc.
    # (matches the bash variant's behaviour — see ralph.template.sh for rationale).
    $curCommitCount = (git rev-list --count HEAD 2>$null)
    if (-not $curCommitCount) { $curCommitCount = 0 }
    $curCommitCount = [int]$curCommitCount
    if ($null -ne $prevCommitCount -and $curCommitCount -lt $prevCommitCount) {
        $consecutiveResetCount += 1
    } else {
        $consecutiveResetCount = 0
    }
    $prevCommitCount = $curCommitCount

    Add-JournalLine "`"items_closed`":$itemsClosed,`"items_added`":$itemsAdded,`"iter_seconds`":$iterSeconds,`"iter_cost_usd`":$iterCost,`"total_cost_usd`":$totalCostUsd,`"iter_exit`":$iterExit"

    "ralph: iter $iter done. closed=$itemsClosed added=$itemsAdded seconds=$iterSeconds cost=$iterCost total=$totalCostUsd" `
        | Tee-Object -FilePath $Journal -Append

    if ($Mode -eq 'single-pass') {
        Write-Host 'SINGLE_PASS_DONE' -ForegroundColor Green
        Add-JournalLine '"exit_reason":"SINGLE_PASS_DONE"'
        break
    }
}

# === Post-loop summary ===
$finalOpen    = @(Select-String -Path $FixPlan -Pattern '^- \[ \]').Count
$finalClosed  = @(Select-String -Path $FixPlan -Pattern '^- \[x\]').Count
$finalElapsed = [int][DateTimeOffset]::Now.ToUnixTimeSeconds() - $startEpoch

@"
# Ralph run report — {{USECASE}}

- **Iterations**: $iter (cap $MaxIterations)
- **Elapsed**: $([math]::Floor($finalElapsed / 60)) min (cap $($MaxHours * 60) min)
- **Cost**: `$$totalCostUsd (cap `$$MaxCostUsd)
- **Items closed**: $finalClosed
- **Items still open**: $finalOpen
- **Branch**: {{BRANCH}}
- **Baseline**: {{BASELINE_SHA}}

## Next actions
1. Read \`fix_plan.md\` — any \`> blocker:\` or \`> human-needed:\` notes need operator review
2. Run \`npm test\` (or equivalent) to confirm full suite is green
3. Spawn R2 review pipeline against the full diff: \`git diff {{BASELINE_SHA}}..HEAD\`
4. If clean, open PR. If not, either run another \`./ralph.ps1\` after editing fix_plan, or \`git reset --hard {{BASELINE_SHA}}\` to abandon.

## Journal
\`Get-Content journal.jsonl\` for per-iteration detail.
"@ | Out-File -Encoding utf8 $Report

"ralph: loop exited. report=$Report" | Tee-Object -FilePath $Journal -Append
